# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'week_2_part_3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'ReachabilitySwift'
  pod 'Alamofire', '~> 3.4'
  pod 'JSONWebToken'

  # Pods for week_2_part_3

  target 'week_2_part_3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'week_2_part_3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
